#!/bin/bash

# Setup script to create Git pre-commit hook
# This script creates a pre-commit hook that runs pre_commit.sh before each commit

echo "Setting up Git pre-commit hook..."

# Create the .git/hooks directory if it doesn't exist
# Note: This assumes we are in a git repo. 
# Since this creates a hook for THIS specific example, it might be tricky if the .git folder is at the root of 'skir' or 'Gepheum'.
# We probably shouldn't install a global git hook for just this example directory unless intended.
# But following the example pattern:

GIT_DIR="$(git rev-parse --git-dir 2>/dev/null)"

if [ -z "$GIT_DIR" ]; then
    echo "❌ Not a git repository. Cannot setup hook."
    exit 1
fi

HOOK_FILE="$GIT_DIR/hooks/pre-commit"

# Helper to add execution of our script to the hook
ADD_HOOK_CMD='
# Run multilingual example checks
./skir/examples/multilingual/pre_commit.sh
if [ $? -ne 0 ]; then
    echo "Multilingual example checks failed."
    exit 1
fi
'

if [ -f "$HOOK_FILE" ]; then
    echo "⚠️  pre-commit hook already exists."
    echo "Please manually add the call to ./skir/examples/multilingual/pre_commit.sh if desired."
else
    mkdir -p "$(dirname "$HOOK_FILE")"
    cat > "$HOOK_FILE" << EOF
#!/bin/bash
# Pre-commit hook
# Generated by skir/examples/multilingual/pre_commit_setup.sh

# Get repo root
REPO_ROOT="\$(git rev-parse --show-toplevel)"
cd "\$REPO_ROOT"

# Run multilingual example checks
if [ -f "skir/examples/multilingual/pre_commit.sh" ]; then
    ./skir/examples/multilingual/pre_commit.sh
    if [ \$? -ne 0 ]; then
        echo "❌ Skir Multilingual Example checks failed."
        exit 1
    fi
fi

echo "✅ Pre-commit checks passed."
EOF
    chmod +x "$HOOK_FILE"
    echo "✅ Created pre-commit hook at $HOOK_FILE"
fi
